directories:
  mirror_module_path: False
  removed_mirror_prefix: "/Users/stephen/Stephencwelch Dropbox/Stephen Welch"
  base: "/Users/stephen/Stephencwelch Dropbox/welch_labs/grokking/manim"
  # base: "/Users/stephen/Stephencwelch Dropbox/welch_labs/double_descent/manim"
  subdirs:
    raster_images: "images/raster"
    vector_images: "images/vector"
    pi_creature_images: "images/pi_creature/svg"
    downloads: "manim_downloads"
    # Use the default value for the rest
universal_import_line: "from manim_imports_ext import *"
window:
  position_string: UR
  monitor_index: 1
  full_screen: False
camera:
  resolution: (3840, 2160) #(7680, 4320) #(3840, 2160) #(7680, 4320) #
  background_color: "#000000" #191519" #"#000000" ##FFFFFF"
  fps: 30
  background_opacity: 1.0
file_writer:
  saturation: 1.5
text:
  font: "CMU Serif"
  alignment: "CENTER"
tex:
  template: "default"
embed:
  autoreload: True
ignore_manimlib_modules_on_reload: True
